=== JigarMehta277/XML-defination-demonstration/books.dtd
<!ELEMENT books (book*)>
<!ELEMENT book (isbn, title, year, language, author+)>


<!ATTLIST book id CDATA #REQUIRED>

<!ELEMENT isbn (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT author (#PCDATA)>

=== JigarMehta277/XML-defination-demonstration/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">

<books>
  <book id="1">
    <isbn>7854568978475</isbn>
    <title>Assassins creed brotherhood</title>
    <year>2018</year>
    <language>English</language>
    <author>Anton Gill</author>
  </book>
  <book id="2">
    <isbn>6571236475368</isbn>
    <title>Back to Whitechapel</title>
    <year>2013</year>
    <language>French</language>
    <author>Michel Moatti</author>
    <author>Lope de Vega</author>
  </book>
  <book id="3">
    <isbn>5674534512357</isbn>
    <title>Don Quixote</title>
    <year>1615</year>
    <language>Spanish</language>
    <author>Miguel de Cervantes</author>
  </book>
</books>
